import { readdir, readFile, writeFile, mkdir, unlink, rmdir } from 'node:fs/promises';

const directory = new URL('../content/notes/', import.meta.url);
const output = new URL('../notes/', import.meta.url);
const files = (await readdir(directory))
  .filter(file => /^[a-z0-9][a-z0-9-]*\.md$/.test(file))
  .sort().reverse();
const slugs = files.map(file => file.slice(0, -3));
const template = await readFile(new URL('./reader-template.html', import.meta.url), 'utf8');
const generatedMarker = '<!-- Generated by scripts/update-notes.mjs; content is loaded from Markdown. -->';

function render(values) {
  return template.replace(/\{\{([A-Z]+)\}\}/g, (_, key) => {
    if (!(key in values)) throw new Error(`Missing template value: ${key}`);
    return values[key];
  });
}

async function writePage(folder, values) {
  await mkdir(folder, { recursive: true });
  const page = new URL('index.html', folder);
  const previous = await readFile(page, 'utf8').catch(error => {
    if (error.code !== 'ENOENT') throw error;
    return null;
  });
  if (previous !== null && !previous.includes(generatedMarker)) throw new Error(`Refusing to overwrite a handwritten page: ${page.pathname}`);
  await writeFile(page, render(values));
}

await mkdir(output, { recursive: true });
for (const slug of slugs) {
  await writePage(new URL(slug + '/', output), {
    KIND: 'note', SLUG: slug, TITLE: '笔记', LABEL: 'FIELD NOTES',
    PATH: `/notes/${slug}/`, SOURCE: `/content/notes/${slug}.md`
  });
}
await writePage(new URL('../resume/', import.meta.url), {
  KIND: 'resume', SLUG: '', TITLE: '个人简历', LABEL: 'CURRICULUM VITAE',
  PATH: '/resume/', SOURCE: '/content/resume.md'
});
// Remove only our generated wrappers when the corresponding Markdown is removed.
for (const entry of await readdir(output, { withFileTypes: true })) {
  if (!entry.isDirectory() || slugs.includes(entry.name)) continue;
  const folder = new URL(entry.name + '/', output);
  const page = new URL('index.html', folder);
  const previous = await readFile(page, 'utf8').catch(error => {
    if (error.code !== 'ENOENT') throw error;
    return '';
  });
  if (previous.includes(generatedMarker)) {
    await unlink(page);
    await rmdir(folder).catch(error => { if (error.code !== 'ENOTEMPTY') throw error; });
  }
}
await writeFile(new URL('index.json', directory), JSON.stringify(files, null, 2) + '\n');
console.log(`已更新 ${files.length} 篇笔记的索引、独立阅读页和简历页面。`);
